dist: xenial
language: python
python:
        - "3.7"
install:
        - pip install -r requirements.txt
script:
        - python london_underground/underground_file_reader.py
        - python london_underground/station.py
        - python london_underground/calculator.py
        - python tests/test_underground_file_reader.py
